name: Build and Push Docker Images

# Trigger events https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  appVersion: 1.0.4

jobs:
  build-and-push:
    runs-on: ubuntu-latest

# Actions from the GitHub Marketplace are pre-built, reusable components that you can use in your GitHub Actions workflows. They are created and shared by the community and provide specific functionality to automate different tasks in your software development workflows.
#  https://github.com/marketplace?type=actions.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

# https://github.com/marketplace/actions/docker-login
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push monolith Docker image
        run: |
          docker build -t dareyregistry/monolith:${{ env.appVersion }} .
          docker push dareyregistry/monolith:${{ env.appVersion }}
